#+title: OpenGMK

*OpenGMK* is a modern rewrite of the proprietary GameMaker Classic engines, providing a full sourceport of the runner, a decompiler, a TASing framework, and libraries for working with gamedata yourself. It's being worked on almost every day! We’re constantly adding new features and updating the code. Please remember that /this project is a work in progress/ and is unreleased. Until there's an official stable release, please note that your savestates may break in future releases.




* About GameMaker Classic & OpenGMK
*GameMaker* (formerly /Game Maker/) is an engine for creating Windows games, originally created by [[https://en.wikipedia.org/wiki/Mark_Overmars][Mark Overmars]] in 1999 and [[https://www.yoyogames.com/][YoYo Games]] since 2007. *GameMaker 8* ("GM8") was the last of the /numbered releases/ of GameMaker,
released on December 22nd 2009 (surpassing /GameMaker 7/) and succeeded by the vastly more popular /GameMaker: Studio/ in 2011.
The pre-Studio versions are often referred to as /GameMaker Classic/. Due to the huge behavioral differences, as well as /Studio/'s lack of backward-compatibility, the classic engines are still very widely used, with thousands of games to their name.

One of GameMaker's original strengths as a game engine was its ability to compile an entire project into a single executable. No external dependencies or installers, just compile, send the =.exe= file to your friend and they will be able to play your game. This is achieved by having the target executable act as a phase file for the entire collection of assets required to run the game. In other words, the executable contains not only the game engine code, but all of the objects, scripts, sprites, room layouts, everything required for the game logic. This behaviour was made optional in /Studio/, giving the creator a choice between a standalone executable or =.msi= installer, however the standalone builds just extract the contents of the installer to a temporary folder when they're launched, so sending the extracted contents as a =.zip= became much more preferable.

This project was originally started as [[https://github.com/Adamcake/Legacy-GM8Emulator][GM8Emulator]], a program that can load /GameMaker Classic/ games, and accurately play the game within. The goal was to have it mimic the original engine as closely as possible, down to the sub-frame and implementation detail (if observable). Strictly speaking, /emulator/ was not the correct term. In computing, an emulator is a piece of software on a computer system which emulates the behaviour of a different computer system. We aren't emulating any computer system, just the engine, unless you consider /Game Maker Language/ its own architecture. A more accurate term would be a /sourceport/, but it didn't sound as cool at the time. The project required us to write a decompiler as a starting point to extract the assets, and since we were already maintaining the most up-to-date fork of [[https://github.com/DatZach][Zach Reedy]]'s [[https://github.com/WastedMeerkat/gm81decompiler][gm81decompiler]] from 2013, we used that as a starting point to develop a much faster version from scratch out of the new codebase, released as [[https://github.com/OpenGMK/GM8Decompiler][GM8Decompiler]], which was originally a separate repository, but the code is now merged into the unified repository we named the *OpenGMK Project*.
* Contributing
This project has only been worked on by a few people so far in their little free time. Contributions are always welcome, although we'd prefer if you got in contact beforehand to discuss details (opening an issue, for example). All contributions are licensed under the same licence as the project.
* Additional Credits
- [[https://github.com/DatZach][DatZach]] for creating the original free and open source decompiler.
- [[https://github.com/Jabberwock-RU][Jabberwock-RU]] for creating the new project icon and logos.
* Licence
OpenGMK is free and open source software, provided under the [[./LICENCE.md][GNU GPL v2]], and is in no way affiliated with /GameMaker™/ or /YoYo Games Ltd./
